version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mailing-api
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8090:80"
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local

  db:
    image: mysql:8.0
    container_name: mailing-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mailing
      MYSQL_USER: mailuser
      MYSQL_PASSWORD: password
    ports:
      - "3310:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
